use_frameworks!

platform :ios, '10.0'

target 'testProject_Example' do
  pod 'testProject', :path => '../'

  target 'testProject_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
